"""baseline schema (v1.1)

Revision ID: 0001
Revises: 
Create Date: 2026-10-06 20:02:46.417866
"""
from alembic import op
import sqlalchemy as sa


revision = '0001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('username', sa.String(length=80), nullable=True),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('target', sa.String(length=512), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_event', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_event_created_at'), ['created_at'], unique=False)

    op.create_table('repository',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('format', sa.String(length=16), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('upstream_url', sa.String(length=255), nullable=True),
    sa.Column('upstream_username', sa.String(length=255), nullable=True),
    sa.Column('upstream_password', sa.String(length=512), nullable=True),
    sa.Column('proxy_mode', sa.String(length=16), server_default='global', nullable=False),
    sa.Column('proxy_url', sa.String(length=512), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('public', sa.Boolean(), nullable=False),
    sa.Column('block_severity', sa.String(length=16), nullable=True),
    sa.Column('allow_redeploy', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('repository', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_repository_name'), ['name'], unique=True)

    op.create_table('setting',
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('value', sa.JSON(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('restrict_deploy', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_username'), ['username'], unique=True)

    op.create_table('api_token',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('prefix', sa.String(length=16), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('api_token', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_api_token_token_hash'), ['token_hash'], unique=True)

    op.create_table('docker_manifest',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('repository_id', sa.Integer(), nullable=False),
    sa.Column('image', sa.String(length=255), nullable=False),
    sa.Column('digest', sa.String(length=100), nullable=False),
    sa.Column('media_type', sa.String(length=255), nullable=False),
    sa.Column('size', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['repository_id'], ['repository.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('repository_id', 'image', 'digest')
    )
    with op.batch_alter_table('docker_manifest', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_docker_manifest_repository_id'), ['repository_id'], unique=False)

    op.create_table('docker_upload',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('repository_id', sa.Integer(), nullable=False),
    sa.Column('image', sa.String(length=255), nullable=False),
    sa.Column('size', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['repository_id'], ['repository.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('package',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('repository_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('meta', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['repository_id'], ['repository.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('repository_id', 'name')
    )
    with op.batch_alter_table('package', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_package_repository_id'), ['repository_id'], unique=False)

    op.create_table('user_deploy_repos',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('repository_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['repository_id'], ['repository.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'repository_id')
    )
    op.create_table('version',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('package_id', sa.Integer(), nullable=False),
    sa.Column('version', sa.String(length=128), nullable=False),
    sa.Column('digest', sa.String(length=100), nullable=True),
    sa.Column('meta', sa.JSON(), nullable=True),
    sa.Column('uploaded_by', sa.String(length=80), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('download_count', sa.Integer(), nullable=False),
    sa.Column('scan_status', sa.String(length=16), nullable=False),
    sa.Column('scan_error', sa.Text(), nullable=True),
    sa.Column('scanned_at', sa.DateTime(), nullable=True),
    sa.Column('scanner', sa.String(length=64), nullable=True),
    sa.Column('count_critical', sa.Integer(), nullable=False),
    sa.Column('count_high', sa.Integer(), nullable=False),
    sa.Column('count_medium', sa.Integer(), nullable=False),
    sa.Column('count_low', sa.Integer(), nullable=False),
    sa.Column('count_unknown', sa.Integer(), nullable=False),
    sa.Column('sbom_key', sa.String(length=255), nullable=True),
    sa.Column('component_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['package_id'], ['package.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('package_id', 'version')
    )
    with op.batch_alter_table('version', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_version_package_id'), ['package_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_version_scan_status'), ['scan_status'], unique=False)

    op.create_table('artifact_file',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('version_id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('size', sa.BigInteger(), nullable=False),
    sa.Column('content_type', sa.String(length=128), nullable=True),
    sa.Column('meta', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['version_id'], ['version.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('artifact_file', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_artifact_file_version_id'), ['version_id'], unique=False)

    op.create_table('download_event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('repository_id', sa.Integer(), nullable=True),
    sa.Column('package_id', sa.Integer(), nullable=True),
    sa.Column('version_id', sa.Integer(), nullable=True),
    sa.Column('format', sa.String(length=16), nullable=True),
    sa.Column('repo_name', sa.String(length=64), nullable=True),
    sa.Column('package_name', sa.String(length=255), nullable=True),
    sa.Column('version_name', sa.String(length=128), nullable=True),
    sa.Column('filename', sa.String(length=255), nullable=True),
    sa.Column('username', sa.String(length=80), nullable=True),
    sa.Column('ip', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.Column('cache_hit', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['package_id'], ['package.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['repository_id'], ['repository.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['version_id'], ['version.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('download_event', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_download_event_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_download_event_package_id'), ['package_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_download_event_repository_id'), ['repository_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_download_event_username'), ['username'], unique=False)
        batch_op.create_index(batch_op.f('ix_download_event_version_id'), ['version_id'], unique=False)

    op.create_table('notification',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('version_id', sa.Integer(), nullable=True),
    sa.Column('repo_name', sa.String(length=64), nullable=True),
    sa.Column('package_name', sa.String(length=255), nullable=True),
    sa.Column('version_name', sa.String(length=128), nullable=True),
    sa.Column('trigger', sa.String(length=16), nullable=True),
    sa.Column('max_severity', sa.String(length=16), nullable=True),
    sa.Column('findings', sa.JSON(), nullable=True),
    sa.Column('recipients', sa.Text(), nullable=True),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['version_id'], ['version.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notification_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_notification_sent_at'), ['sent_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_notification_version_id'), ['version_id'], unique=False)

    op.create_table('vulnerability',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('version_id', sa.Integer(), nullable=False),
    sa.Column('vuln_id', sa.String(length=64), nullable=False),
    sa.Column('pkg_name', sa.String(length=255), nullable=True),
    sa.Column('pkg_type', sa.String(length=64), nullable=True),
    sa.Column('installed_version', sa.String(length=128), nullable=True),
    sa.Column('fixed_version', sa.String(length=255), nullable=True),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('url', sa.String(length=512), nullable=True),
    sa.Column('source', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['version_id'], ['version.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('vulnerability', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_vulnerability_version_id'), ['version_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_vulnerability_vuln_id'), ['vuln_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vulnerability', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vulnerability_vuln_id'))
        batch_op.drop_index(batch_op.f('ix_vulnerability_version_id'))

    op.drop_table('vulnerability')
    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notification_version_id'))
        batch_op.drop_index(batch_op.f('ix_notification_sent_at'))
        batch_op.drop_index(batch_op.f('ix_notification_created_at'))

    op.drop_table('notification')
    with op.batch_alter_table('download_event', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_download_event_version_id'))
        batch_op.drop_index(batch_op.f('ix_download_event_username'))
        batch_op.drop_index(batch_op.f('ix_download_event_repository_id'))
        batch_op.drop_index(batch_op.f('ix_download_event_package_id'))
        batch_op.drop_index(batch_op.f('ix_download_event_created_at'))

    op.drop_table('download_event')
    with op.batch_alter_table('artifact_file', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_artifact_file_version_id'))

    op.drop_table('artifact_file')
    with op.batch_alter_table('version', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_version_scan_status'))
        batch_op.drop_index(batch_op.f('ix_version_package_id'))

    op.drop_table('version')
    op.drop_table('user_deploy_repos')
    with op.batch_alter_table('package', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_package_repository_id'))

    op.drop_table('package')
    op.drop_table('docker_upload')
    with op.batch_alter_table('docker_manifest', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_docker_manifest_repository_id'))

    op.drop_table('docker_manifest')
    with op.batch_alter_table('api_token', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_api_token_token_hash'))

    op.drop_table('api_token')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_username'))

    op.drop_table('user')
    op.drop_table('setting')
    with op.batch_alter_table('repository', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_repository_name'))

    op.drop_table('repository')
    with op.batch_alter_table('audit_event', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_event_created_at'))

    op.drop_table('audit_event')
    # ### end Alembic commands ###
