"""os packages (deb, rpm, apk) and proxy cache retention

Revision ID: 0002
Revises: 0001
Create Date: 2026-10-06 20:21:38.406689
"""
from alembic import op
import sqlalchemy as sa


revision = '0002'
down_revision = '0001'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('repo_file',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('repository_id', sa.Integer(), nullable=False),
    sa.Column('path', sa.String(length=512), nullable=False),
    sa.Column('digest', sa.String(length=100), nullable=False),
    sa.Column('size', sa.BigInteger(), nullable=False),
    sa.Column('content_type', sa.String(length=128), nullable=True),
    sa.Column('fetched_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['repository_id'], ['repository.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('repository_id', 'path')
    )
    with op.batch_alter_table('repo_file', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_repo_file_repository_id'), ['repository_id'], unique=False)

    with op.batch_alter_table('artifact_file', schema=None) as batch_op:
        batch_op.add_column(sa.Column('path', sa.String(length=512), nullable=True))
        batch_op.create_index(batch_op.f('ix_artifact_file_path'), ['path'], unique=False)

    with op.batch_alter_table('repository', schema=None) as batch_op:
        batch_op.add_column(sa.Column('distro', sa.String(length=32), nullable=True))
        batch_op.add_column(sa.Column('cache_retention_days', sa.Integer(), nullable=True))

    with op.batch_alter_table('version', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_accessed_at', sa.DateTime(), nullable=True))
        batch_op.create_index(batch_op.f('ix_version_last_accessed_at'), ['last_accessed_at'], unique=False)

    # ### end Alembic commands ###

    # data migration: existing versions get their last access from the download history, so that the new
    # cache retention does not treat everything pulled before the upgrade as "never used"
    op.execute("UPDATE version SET last_accessed_at = (SELECT max(download_event.created_at) FROM download_event "
               "WHERE download_event.version_id = version.id)")


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('version', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_version_last_accessed_at'))
        batch_op.drop_column('last_accessed_at')

    with op.batch_alter_table('repository', schema=None) as batch_op:
        batch_op.drop_column('cache_retention_days')
        batch_op.drop_column('distro')

    with op.batch_alter_table('artifact_file', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_artifact_file_path'))
        batch_op.drop_column('path')

    with op.batch_alter_table('repo_file', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_repo_file_repository_id'))

    op.drop_table('repo_file')
    # ### end Alembic commands ###
