"""scan ownership for multiple workers

Revision ID: 0003
Revises: 0002
Create Date: 2026-10-06 20:50:43.824802
"""
from alembic import op
import sqlalchemy as sa


revision = '0003'
down_revision = '0002'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('version', schema=None) as batch_op:
        batch_op.add_column(sa.Column('scan_worker', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('scan_started_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('version', schema=None) as batch_op:
        batch_op.drop_column('scan_started_at')
        batch_op.drop_column('scan_worker')

    # ### end Alembic commands ###
